### ISSUE TITLE
Automate data_fetch_benign.py

### ISSUE THREAD

**Issue by isumit19** [Anmol-Sharma/URL_CLASSIFICATION_SYSTEM#1]
Can we automate the benign URL extraction from the DMOZ website? As it requires input by the user, again and again, it would be better if it can generate URLs the same as the malicious ones from PhishTank.
@Anmol-Sharma

**Comment by Anmol-Sharma** [comment]
Hello @isumit19 👋 

First of all, thanks for checking out this repository. Most of the code on this repository is very outdated as I wrote most of it in early 2016.

Back then, web scrapping tools in python were still coming up and I wasn't aware of tools like Scrapy and BeaufifulSoup, so I just wrote some barebones code to simply generate Http Get request and then parse the pages to scrap URLs using simple regular expressions. As far as I remember, that keyboard input was put in place, as we had to manually enter page URL(s) from DMOZ, because the URL(s) did follow a simple pattern like :-

```
https://dmoz-odp.org/Computers/Computer_Science/Computer_Graphics/1
https://dmoz-odp.org/Computers/Computer_Science/Computer_Graphics/2
...
```
Or simply did not exist.

If you are looking to mine data from those websites, my suggestion will be to use [Scrapy](https://scrapy.org/) or [BeautifulSoup](https://www.crummy.com/software/BeautifulSoup/bs4/doc/), as they are much more robust and mature tools which will save you time and do a better job.

Also, I should mention that DMOZ has been discontinued and has not updated its data since 2017, but PhishTank is still active. So for Malign Urls write something using Scrapy to scrap data from PhishTank and for Benign Url(s) you will have to look up some other sources, where you can find a list Benign of urls and then use the same procedure to extract the list of URL(s) there.

Hope This Help! 🙂

**Comment by isumit19** [comment]
Thanks for the info 👍 🙂
